<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Integration/CartSettingsInterface.php
 */

interface Brontosoftware_Magento_Integration_CartSettingsInterface
{
    const XML_PATH_RECOVERY_ENABLED = 'brontosoftware/integration/extensions/cart_recovery/enabled';
    const XML_PATH_RECOVERY_EMBED = 'brontosoftware/integration/extensions/cart_recovery/embed_code';

    /**
     * Is Cart Recovery enabled?
     *
     * @param string $scopeType
     * @param mixed $scopeId
     * @return boolean
     */
    public function isCartRecoveryEnabled($scopeType = 'default', $scopeId = null);

    /**
     * Gets the pasted cart recovery embed code
     *
     * @param string $scopeType
     * @param mixed $scopeId
     * @return string
     */
    public function getCartRecoveryEmbedCode($scopeType = 'default', $scopeId = null);

    /**
     * Based on the saved cart, get email address for recovery
     *
     * @param mixed $quote
     * @return string
     */
    public function getCartRecoveryEmail($quote);

    /**
     * Gets an appropriate redirect for loading the model's page
     *
     * @param mixed $modelId
     * @param mixed $store
     * @param string $modelType
     */
    public function getRedirectUrl($modelId, $store, $modelType = 'cart');

    /**
     * Determines if the shadow dom should be written
     *
     * @param string $scopeType
     * @param mixed $scopeId
     * @return boolean
     */
    public function isShadowDom($scopeType = 'default', $scopeId = null);
}
