<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Integration/PopupSettings.php
 */

class Brontosoftware_Magento_Integration_PopupSettings extends Brontosoftware_Magento_Core_Config_ContainerAbstract implements Brontosoftware_Magento_Integration_PopupSettingsInterface
{
    /**
     * @see parent
     */
    public function isPopupEnabled($scopeType = 'default', $scopeId = null)
    {
        return $this->_config->isSetFlag(self::XML_PATH_POPUP_ENABLED, $scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function getPopupDomains($scopeType = 'default', $scopeId = null)
    {
        $domains = $this->_config->getValue(self::XML_PATH_POPUP_DOMAINS, $scopeType, $scopeId);
        if (is_array($domains)) {
            return $domains;
        }
        return explode(',', $domains);
    }

    /**
     * @see parent
     */
    public function isCreateSubscribers($scopeType = 'default', $scopeId = null)
    {
        return $this->_config->isSetFlag(self::XML_PATH_POPUP_CREATE, $scopeType, $scopeId);
    }
}
