<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Integration/Settings.php
 */

class Brontosoftware_Magento_Integration_Settings implements Brontosoftware_Magento_Integration_SettingsInterface
{
    protected $_carts;
    protected $_popups;
    protected $_coupons;

    /**
     * @param Brontosoftware_Magento_Integration_CartSettingsInterface $carts
     * @param Brontosoftware_Magento_Integration_PopupSettingsInterface $popups
     * @param Brontosoftware_Magento_Integration_CouponSettingsInterface $coupons
     */
    public function __construct(
        Brontosoftware_Magento_Integration_CartSettingsInterface $carts,
        Brontosoftware_Magento_Integration_PopupSettingsInterface $popups,
        Brontosoftware_Magento_Integration_CouponSettingsInterface $coupons
    ) {
        $this->_carts = $carts;
        $this->_popups = $popups;
        $this->_coupons = $coupons;
    }

    /**
     * @see parent
     */
    public function isPopupEnabled($scopeType = 'default', $scopeId = null)
    {
        return $this->_popups->isPopupEnabled($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function getPopupDomains($scopeType = 'default', $scopeId = null)
    {
        return $this->_popups->getPopupDomains($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function isCreateSubscribers($scopeType = 'default', $scopeId = null)
    {
        return $this->_popups->isCreateSubscribers($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function isCouponEnabled($scopeType = 'default', $scopeId = null)
    {
        return $this->_coupons->isCouponEnabled($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function isCartRecoveryEnabled($scopeType = 'default', $scopeId = null)
    {
        return $this->_carts->isCartRecoveryEnabled($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function getCartRecoveryEmbedCode($scopeType = 'default', $scopeId = null)
    {
        return $this->_carts->getCartRecoveryEmbedCode($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function getCartRecoveryEmail($quote)
    {
        return $this->_carts->getCartRecoveryEmail($quote);
    }

    /**
     * @see parent
     */
    public function getRedirectUrl($modelId, $store, $modelType = 'cart')
    {
        return $this->_carts->getRedirectUrl($modelId, $store, $modelType);
    }

    /**
     * @see parent
     */
    public function isShadowDom($scopeType = 'default', $scopeId = null)
    {
        return $this->_carts->isShadowDom($scopeType, $scopeId);
    }

    /**
     * @see parent
     */
    public function generateUUID()
    {
        return sprintf('%04x%04x-%04x-%04x-%04x-%04x%04x%04x',
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ),
            mt_rand( 0, 0xffff ),
            mt_rand( 0, 0x0fff ) | 0x4000,
            mt_rand( 0, 0x3fff ) | 0x8000,
            mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff ), mt_rand( 0, 0xffff )
        );
    }
}
