<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Context/Custom.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Context_Custom implements Brontosoftware_Magento_Recommendation_Collect_ContextInterface
{
    protected $_items;
    protected $_customerId;
    protected $_storeId;

    /**
     * @param array $items
     * @param mixed $storeId
     * @param mixed $customerId
     */
    public function __construct(
        $items = array(),
        $storeId = null,
        $customerId = null
    ) {
        $this->_items = $items;
        $this->_customerId = $customerId;
        $this->_storeId = $storeId;
    }

    /**
     * @see parent
     */
    public function getContextItems()
    {
        $items = array();
        foreach ($this->_items as $itemId => $item) {
            if (is_numeric($item)) {
                $itemId = $item;
            }
            $items[$itemId] = array(false, $itemId);
        }
        return $items;
    }

    /**
     * @see parent
     */
    public function getCustomerId()
    {
        return $this->_customerId;
    }

    /**
     * @see parent
     */
    public function getStoreId()
    {
        return $this->_storeId;
    }

    /**
     * @see parent
     */
    public function getContextType()
    {
        return self::TYPE_CUSTOM;
    }

    /**
     * @see parent
     */
    public function getContextId()
    {
        return self::TYPE_CUSTOM;
    }
}
