<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Context/Nothing.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Context_Nothing implements Brontosoftware_Magento_Recommendation_Collect_ContextInterface
{
    /**
     * @see parent
     */
    public function getContextType()
    {
        return self::TYPE_EMPTY;
    }

    /**
     * @see parent
     */
    public function getContextItems()
    {
        return array();
    }

    /**
     * @see parent
     */
    public function getCustomerId()
    {
        return null;
    }

    /**
     * @see parent
     */
    public function getStoreId()
    {
        return null;
    }

    /**
     * @see parent
     */
    public function getContextId()
    {
        return null;
    }
}
