<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Source/Manualproducts.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Source_Manualproducts implements Brontosoftware_Magento_Recommendation_Collect_SourceInterface
{
    protected $_promotion;

    /**
     * @param array $promotion
     */
    public function __construct($promotion)
    {
        $this->_promotion = $promotion;
    }

    /**
     * @see parent
     */
    public function collect(Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context)
    {
        return $this->_promotion['products'];
    }
}
