<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Source/Manualcategory.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Source_Manualcategory implements Brontosoftware_Magento_Recommendation_Collect_SourceInterface
{
    protected $_promotion;
    protected $_categoryRepo;

    /**
     * @param array $promotion
     * @param Brontosoftware_Magento_Core_Catalog_CategoryCacheInterface $categoryRepo
     */
    public function __construct(
        $promotion,
        Brontosoftware_Magento_Core_Catalog_CategoryCacheInterface $categoryRepo
    ) {
        $this->_promotion = $promotion;
        $this->_categoryRepo = $categoryRepo;
    }

    /**
     * @see parent
     */
    public function collect(Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context)
    {
        $items = array();
        $limit = $this->_promotion['limit'];
        foreach ($this->_promotion['categories'] as $categoryId) {
            $category = $this->_categoryRepo->getById($categoryId);
            if ($category) {
                $products = $category->getProductCollection()->setPageSize($limit);
                foreach ($products as $product) {
                    $items[] = $product->getId();
                    $limit--;
                    if ($limit <= 0) {
                        break 2;
                    }
                }
            }
        }
        return $items;
    }
}
