<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Source/Markednew.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Source_Markednew implements Brontosoftware_Magento_Recommendation_Collect_SourceInterface
{
    const DATETIME_INTERNAL_FORMAT = 'Y-m-d';

    protected $_factory;
    protected $_promotion;

    /**
     * @param array $promotion
     * @param Brontosoftware_Magento_Core_Report_CollectionFactoryInterface $factory
     */
    public function __construct(
        $promotion,
        Brontosoftware_Magento_Core_Report_CollectionFactoryInterface $factory
    ) {
        $this->_promotion = $promotion;
        $this->_factory = $factory;
    }

    /**
     * @see parent
     */
    public function collect(Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context)
    {
        $thirtyDays = strtotime('-' . $this->_promotion['threshold'] . ' days');
        $toDate = date(self::DATETIME_INTERNAL_FORMAT);
        $fromDate = date(self::DATETIME_INTERNAL_FORMAT, $thirtyDays);
        $newProducts = $this->_factory->getNewProducts()
            ->addStoreFilter($context->getStoreId())
            ->addAttributeToFilter('news_from_date', array('or' => array(
                0 => array('date' => true, 'to' => $toDate),
                1 => array('is' => 'NULL'))
            ), 'left')
            ->addAttributeToFilter('news_to_date', array('or' => array(
                0 => array('date' => true, 'from' => $fromDate),
                1 => array('is' => 'NULL'))
            ), 'left')
            ->addAttributeToFilter(
                array(
                    array('attribute' => 'news_from_date', 'is' => 'NOT NULL'),
                    array('attribute' => 'news_to_date', 'is' => 'NOT NULL')
                )
            )
            ->addAttributeToSort('news_from_date', 'desc')
            ->setPageSize($this->_promotion['limit']);
        $items = array();
        foreach ($newProducts as $product) {
            $items[] = $product->getId();
        }
        return $items;
    }
}
