<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/Source/Related.php
 */


class Brontosoftware_Magento_Recommendation_Collect_Source_Related implements Brontosoftware_Magento_Recommendation_Collect_SourceInterface
{
    protected $_product;
    protected $_promotion;

    /**
     * @param array $promotion
     * @param mixed $product
     */
    public function __construct($promotion, $product = null)
    {
        $this->_promotion = $promotion;
        $this->_product = $product;
    }

    /**
     * @see parent
     */
    public function collect(Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context)
    {
        if (is_null($this->_product)) {
            return array();
        }
        return $this->_product->getRelatedProductIds();
    }
}
