<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/ContextInterface.php
 */

interface Brontosoftware_Magento_Recommendation_Collect_ContextInterface
{
    const TYPE_CUSTOM = 'custom';
    const TYPE_CART = 'quote';
    const TYPE_ORDER = 'order';
    const TYPE_EMPTY = 'nothing';
    const TYPE_INVOICE = 'invoice';
    const TYPE_SHIPMENT = 'shipment';
    const TYPE_WISHLIST = 'wishlist';

    /**
     * Returns the underlying model's id
     *
     * @return mixed
     */
    public function getContextId();

    /**
     * Gets the iterative items in the provided context
     *
     * @return mixed
     */
    public function getContextItems();

    /**
     * Gets the customer ID associated to the context
     *
     * @return mixed
     */
    public function getCustomerId();

    /**
     * Gets the store ID associated to the context
     *
     * @return mixed
     */
    public function getStoreId();

    /**
     * Gets the context type code identifying this context
     *
     * @return string
     */
    public function getContextType();
}
