<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/ContextFactoryInterface.php
 */

interface Brontosoftware_Magento_Recommendation_Collect_ContextFactoryInterface
{
    /**
     * Creates a context with the provided object
     *
     * @param mixed $object
     * @return Brontosoftware_Magento_Recommendation_Collect_ContextInterface
     */
    public function create($object);

    /**
     * Gets a context from a type and model Id
     *
     * @param string $contextType
     * @param mixed $modelId
     * @return Brontosoftware_Magento_Recommendation_Collect_ContextInterface
     */
    public function get($contextType, $modelId);
}
