<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/ContextAbstract.php
 */

abstract class Brontosoftware_Magento_Recommendation_Collect_ContextAbstract implements Brontosoftware_Magento_Recommendation_Collect_ContextInterface
{
    protected $_item;
    protected $_items;

    /**
     * @param mixed $item
     */
    public function __construct($item)
    {
        $this->_item = $item;
    }

    /**
     * @see parent
     */
    public function getContextItems()
    {
        if (is_null($this->_items)) {
            $this->_items = array();
            foreach ($this->_item->getAllItems() as $lineItem) {
                $productId = $lineItem->getProductId();
                if ($lineItem->getParentItemId()) {
                    $parentTuple = array($lineItem->getParentItem(), $productId);
                } else {
                    $parentTuple = array(false, $productId);
                }
                $this->_items[$productId] = $parentTuple;
            }
        }
        return $this->_items;
    }

    /**
     * @see parent
     */
    public function getCustomerId()
    {
        return $this->_item->getCustomerId();
    }

    /**
     * @see parent
     */
    public function getStoreId()
    {
        return $this->_item->getStoreId();
    }
}
