<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/Collect/SourceInterface.php
 */

interface Brontosoftware_Magento_Recommendation_Collect_SourceInterface
{
    const TYPE_INITIAL = 'initial';
    const TYPE_NEW = 'markednew';
    const TYPE_BESTSELLER = 'bestsellers';
    const TYPE_VIEWED = 'viewed';
    const TYPE_RELATED = 'related';
    const TYPE_CROSSSELL = 'crosssell';
    const TYPE_UPSELL = 'upsell';
    const TYPE_MANUALPRODUCTS = 'manualproducts';
    const TYPE_MANUALCATGORY = 'manualcategory';

    /**
     * Collects items based on the surrounding context
     *
     * @param Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context
     * @return array
     */
    public function collect(Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context);
}
