<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Event/ContextProviderInterface.php
 */

interface Brontosoftware_Magento_Connector_Event_ContextProviderInterface
{
    /**
     * Creates an event context from a concrete object
     *
     * @param mixed $object
     * @return array
     */
    public function create($object);
}
