<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Event/PlatformInterface.php
 */

interface Brontosoftware_Magento_Connector_Event_PlatformInterface
{
    /**
     * Annotate an event with infromation
     *
     * @param Brontosoftware_Magento_Connector_Model_Event_SourceInterface $source
     * @param mixed $object
     * @param string $action
     * @param mixed $storeId
     * @param array $context
     * @return array
     */
    public function annotate(Brontosoftware_Magento_Connector_Event_SourceInterface $source, $object, $action = null, $storeId = null, $context = array());

    /**
     * Dispatches an annotated event
     *
     * @param array $event
     * @return boolean
     */
    public function dispatch($event);
}
