<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Event/SourceInterface.php
 */

interface Brontosoftware_Magento_Connector_Event_SourceInterface
{
    const ADD_ACTION = 'add';
    const UPDATE_ACTION = 'update';
    const DELETE_ACTION = 'delete';
    const REPLACE_ACTION = 'replace';

    /**
     * Transform arbitrary Magento data into a consumable event
     *
     * @param mixed $object
     * @return array
     */
    public function transform($object);

    /**
     * Determines which action the object should be
     *
     * @param mixed $object
     * @return string
     */
    public function action($object);

    /**
     * Gets the handled event type
     *
     * @return string
     */
    public function getEventType();
}
