<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Contact/Event/GuestFromOrder.php
 */

class Brontosoftware_Magento_Contact_Event_GuestFromOrder implements Brontosoftware_Magento_Connector_Event_SourceInterface, Brontosoftware_Magento_Connector_Event_ContextProviderInterface
{
    protected $_helper;

    /**
     * @param Brontosoftware_Magento_Contact_SettingsInterface $helper
     */
    public function __construct(
        Brontosoftware_Magento_Contact_SettingsInterface $helper
    ) {
        $this->_helper = $helper;
    }

    /**
     * @see parent
     */
    public function create($order)
    {
        return array(
            'type' => 'order',
            'uniqueKey' => 'contact.order.' . $order->getId()
        );
    }

    /**
     * @see parent
     */
    public function getEventType()
    {
        return 'contact';
    }

    /**
     * @see parent
     */
    public function action($order)
    {
        return $order->getCustomerIsGuest() ? 'add' : '';
    }

    /**
     * @see parent
     */
    public function transform($order)
    {
        return array(
            'email' => $order->getCustomerEmail(),
            'status' => 'transactional',
            'fields' => $this->_helper->getFieldsForModel($order, $order->getStore(), 'order')
        );
    }
}
