<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Customer/GroupCacheInterface.php
 */

interface Brontosoftware_Magento_Core_Customer_GroupCacheInterface
{
    /**
     * Gets a customer group by the group id
     *
     * @param int $groupId
     * @return mixed
     */
    public function getById($groupId);
}
