<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Customer/SessionInterface.php
 */

interface Brontosoftware_Magento_Core_Customer_SessionInterface
{
    /**
     * Gets a customer object from the session
     *
     * @return mixed
     */
    public function getCustomer();

    /**
     * Log out the customer is session
     *
     * @return void
     */
    public function logout();

    /**
     * Sets the before auth url for post logins
     *
     * @param string $redirectUrl
     * @return void
     */
    public function setBeforeAuthUrl($redirectUrl);
}
