<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Catalog/CategoryCacheInterface.php
 */

interface Brontosoftware_Magento_Core_Catalog_CategoryCacheInterface
{
    /**
     * Retrieves the catalog from a local cache or pulls a fresh one
     *
     * @param mixed $catalogId
     * @param mixed $storeId
     * @return mixed
     */
    public function getById($catalogId, $storeId = null);

    /**
     * Retrieves a list of categories based on the source object
     *
     * @param Brontosoftware_Magento_Connector_Discovery_Source $source
     * @return mixed
     */
    public function getBySource(Brontosoftware_Magento_Connector_Discovery_Source $source);
}
