<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Catalog/ImageHelperInterface.php
 */

interface Brontosoftware_Magento_Core_Catalog_ImageHelperInterface
{
    /**
     * Attempts to initializes the product image
     *
     * @param mixed product
     * @param string $attribute
     * @return $this
     */
    public function getImageUrl($product, $attribute);

    /**
     * Attempts to get the default placeholder image
     *
     * @return string
     */
    public function getDefaultPlaceHolderUrl();
}
