<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Catalog/ProductCategoryResolverImpl.php
 */

class Brontosoftware_Magento_Core_Catalog_ProductCategoryResolverImpl implements Brontosoftware_Magento_Core_Catalog_ProductCategoryResolverInterface
{
    protected $_categoryRepo;
    protected $_resolverFactory;

    /**
     * @param Brontosoftware_Magento_Core_Catalog_CategoryCacheInterface $categoryRepo
     * @param Brontosoftware_Magento_Core_Catalog_CategoryResolverFactoryInterface $resolverFactory
     */
    public function __construct(
        Brontosoftware_Magento_Core_Catalog_CategoryCacheInterface $categoryRepo,
        Brontosoftware_Magento_Core_Catalog_CategoryResolverFactoryInterface $resolverFactory
    ) {
        $this->_categoryRepo = $categoryRepo;
        $this->_resolverFactory = $resolverFactory;
    }

    /**
     * @see parent
     */
    public function getCategory($product, $resolver = 'single')
    {
        $branches = array();
        $currentBranch = array();
        $currentPrefix = '';
        foreach ($product->getCategoryIds() as $categoryId) {
            $category = $this->_categoryRepo->getById($categoryId, $product->getStoreId());
            if ($category && $category->getLevel() > 1 ) {
                if (empty($currentPrefix) || !preg_match('|^' . $currentPrefix . '|', $category->getPath())) {
                    if (!empty($currentBranch)) {
                        $branches[] = $currentBranch;
                    }
                    $currentPrefix = $category->getPath();
                    $currentBranch = array();
                }
                $currentBranch[] = $category;
            }
        }
        if (!empty($currentBranch)) {
            $branches[] = $currentBranch;
        }
        return $this->_resolverFactory->create($resolver, $product)->resolve($branches);
    }
}
