<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Catalog/ProductAttributeCacheInterface.php
 */

interface Brontosoftware_Magento_Core_Catalog_ProductAttributeCacheInterface
{
    /**
     * Returns a collection of attributes that have labels
     *
     * @return mixed
     */
    public function getOptionArray();

    /**
     * Returns raw collection of attributes objects
     *
     * @return mixed
     */
    public function getCollection();
}
