<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Recommendation/SettingsInterface.php
 */

interface Brontosoftware_Magento_Recommendation_SettingsInterface extends Brontosoftware_Magento_Connector_Event_HelperInterface
{
    const XML_PATH_ENABLED = 'brontosoftware/recommendation/extensions/settings/enabled';
    const XML_PATH_DESCRIPTION = 'brontosoftware/recommendation/extensions/settings/description';
    const XML_PATH_IMAGE = 'brontosoftware/recommendation/extensions/settings/image_type';
    const XML_PATH_TRUNCATED = 'brontosoftware/recommendation/extensions/settings/truncated';
    const XML_PATH_DESC_LENGTH = 'brontosoftware/recommendation/extensions/settings/descLength';
    const XML_PATH_PROMOTION_OBJECTS = 'brontosoftware/recommendation/objects/promotion/%';
    const XML_PATH_AUTO_REFRESH = 'brontosoftware/recommendation/extensions/settings/autoRefresh';
    const XML_PATH_UPDATE_THRESHOLD = 'brontosoftware/recommendation/extensions/settings/interval';
    const XML_PATH_DISPLAY_SYMBOL = 'brontosoftware/recommendation/extensions/settings/displaySymbol';

    /**
     * Allows auto freshing initiated by the platform
     *
     * @param string $scopeType
     * @param mixed $scopeId
     * @return boolean
     */
    public function isAutoRefreshing($scopeType = 'default', $scopeId = null);

    /**
     * Gets the list of configurable sources on a promotion
     *
     * @return array
     */
    public function getSources();

    /**
     * Gets the recommendation promotion defined in Connector
     *
     * @param mixed $promotionId
     * @param mixed $storeId
     * @param boolean $forceEnable
     * @return mixed
     */
    public function getPromotion($promotionId, $storeId = null, $forceEnable = false);

    /**
     * Provided a product get a truncated (or not) description
     *
     * @param mixed $product
     * @param string $attribute
     * @return string
     */
    public function getDescription($product, $attribute = 'description');

    /**
     * Gets the delivery fields as part of recommendation resolution
     *
     * @param mixed $promotion
     * @param mixed $context
     * @return array
     */
    public function getFields($promotion, Brontosoftware_Magento_Recommendation_Collect_ContextInterface $context = null);

    /**
     * Gets all of the recommendations defined for the registration
     *
     * @param Brontosoftware_Magento_Connector_RegistrationInterface $registration
     * @return array
     */
    public function getAll(Brontosoftware_Magento_Connector_RegistrationInterface $registration);

    /**
     * Determines if is time to refresh
     *
     * @param mixed $lastUpdate
     * @param mixed $threshold
     * @return boolean
     */
    public function isRefreshable($lastUpdate, $threshold = null);

    /**
     * Gets a collection of the report keys configured on this registration
     *
     * @param Brontosoftware_Magento_Connector_RegistrationInterface $registration
     * @return array
     */
    public function getRefreshableKeys(Brontosoftware_Magento_Connector_RegistrationInterface $registration);
}
