<div class="box-collateral box-reviews row" id="customer-reviews">
    <div class="col-md-12">

        <div class="review-iframe">
            <?php $reviewsUrl = $this->getProduct()->getReviewsUrl(); ?>
            <?php if (!empty($reviewsUrl)) : ?>
                <h2>Customer Reviews</h2>
                <iframe src="<?php echo $reviewsUrl; ?>" frameborder="0" scrolling="0"></iframe>
            <?php endif; ?>
        </div>

    </div>
</div>