<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/TargetRule/IndexFactoryInterface.php
 */

interface Brontosoftware_Magento_TargetRule_IndexFactoryInterface
{
    /**
     * Gets a target rule collection based on the source
     *
     * @return mixed
     */
    public function create();
}
