<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/TargetRule/SettingsInterface.php
 */

interface Brontosoftware_Magento_TargetRule_SettingsInterface
{
    /**
     * Exists for Magento
     *
     * @param int number
     * @return int
     */
    public function getMaxProductsListResult($number = 0);

    /**
     * Exists for Magento
     *
     * @param mixed $type
     * @return int
     */
    public function getMaximumNumberOfProduct($type);

    /**
     * Exists for Magento
     *
     * @param mixed $type
     * @return int
     */
    public function getShowProducts($type);

    /**
     * Exists for Magento
     *
     * @param mixed $type
     * @param array $productIds
     * @return array
     */
    public function rotate($type, $productIds);
}
