<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Redemption/ExtensionAbstract.php
 */

abstract class Brontosoftware_Magento_Redemption_ExtensionAbstract extends Brontosoftware_Magento_Connector_Discovery_ExtensionPushEventAbstract
{
    /**
     * Adds an API dropdown to the integration extension
     *
     * @param mixed $observer
     * @return void
     */
    public function integrationAdditional($observer)
    {
        $observer->getEndpoint()->addFieldToExtension('coupon_manager', array(
            'id' => 'toggle_api',
            'name' => $this->translate('Type'),
            'type' => 'select',
            'position' => 3,
            'typeProperties' => array(
                'default' => 'api',
                'options' => array(
                    array(
                        'id' => 'api',
                        'name' => $this->translate('API')
                    ),
                    array(
                        'id' => 'js',
                        'name' => $this->translate('JavaScript')
                    )
                )
            )
        ));
    }

    /**
     * @see parent
     */
    protected function _getObject($observer)
    {
        return $observer->getOrder();
    }
}
