<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Redemption/SettingsInterface.php
 */

interface Brontosoftware_Magento_Redemption_SettingsInterface extends Brontosoftware_Magento_Connector_Event_HelperInterface
{
    const XML_PATH_API_TOGGLE = 'brontosoftware/integration/extensions/coupon_manager/toggle_api';

    /**
     * Determines if the user has turned on REST API intergration
     *
     * @param string $scope
     * @param mixed $scopeId
     * @return boolean
     */
    public function isToggled($scope = 'default', $scopeId = null);
}
