<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Subscriber/ManagerInterface.php
 */

interface Brontosoftware_Magento_Core_Subscriber_ManagerInterface
{
    const LOCATION_DEFAULT = 'normal';
    const LOCATION_CHECKOUT = 'checkout';
    const LOCATION_BRONTO = 'bronto';

    /**
     * Gets a subscriber by id
     *
     * @param mixed $subscriberId
     * @return mixed
     */
    public function getById($subscriberId);

    /**
     * Gets a subscriber by the email address
     *
     * @param mixed $email
     * @return mixed
     */
    public function getByEmail($email);

    /**
     * Gets an iterable from the platform for subscribers
     *
     * @return mixed
     */
    public function getCollection();

    /**
     * Unsubscribes locally the email in the platform
     *
     * @param string $email
     * @param boolean $ignoreStatus
     * @param string $location
     * @return boolean
     */
    public function unsubscribe($email, $ignoreStatus = false, $location = 'normal');

    /**
     * Forcefully subscribes a email in the platform
     *
     * @param string $mixed
     * @param boolean $ignoreStatus
     * @param string $location
     * @return boolean
     */
    public function subscribe($email, $ignoreStatus = false, $location = 'normal');
}
