<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>


<?php foreach ($posts as $post): ?>
    <div class="postWrapper">

        <div>
            <a href="<?php echo $post->getAddress(); ?>"><img
                    src="<?php echo Mage::getBaseUrl('media') . $post->getImage(); ?>" class="post_image" alt=""></a>
        </div>

        <div>
            <div class="postTitle">
                <h2><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h2>
            </div>

            <div class="postContent"><?php echo $post->getPostContent(); ?></div>

            <?php echo $this->getBookmarkHtml($post) ?>

            <div class="postDetails">
                <?php if ($this->getCommentsEnabled()): ?>
                <?php endif; ?>
                <?php $postCats = $post->getCats(); ?>
                <?php if (!empty($postCats)): ?>
                    <?php foreach ($postCats as $data): ?>
                    <?php endforeach; ?>
                <?php else: ?>

                <p class="blue_name"><?php endif; ?><?php echo $post->getUser(); ?></p>

                <?php $date = $post->getCreatedTime();
                $dateToShow = date('j F Y', strtotime($date)); ?>

                <h3><?php echo $dateToShow; ?></h3>
            </div>

        </div>

    </div>
<?php endforeach; ?>
