<?php $posts = $this->getPosts(); ?>
<?php if (count($posts)): ?>
    <!-- --><?php //echo $this->getChildHtml('blog_comments_toolbar'); ?>
    <?php foreach ($posts as $post): ?>
        <div class="postWrapper">
            <div>
                <a href="<?php echo $post->getAddress(); ?>"><img
                        src="<?php echo Mage::getBaseUrl('media') . $post->getImage(); ?>" class="post_image"
                        alt=""></a>
            </div>
            <div>
                <div class="postTitle">
                    <h2><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></h2>
                    <!--                <h3>--><?php //echo $post->getCreatedTime(); ?><!--</h3>-->
                </div>

                <div class="postContent"><?php echo $post->getPostContent(); ?></div>
                <?php echo $this->getBookmarkHtml($post) ?>
<!--                <div class="tags">--><?php //echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?><!--</div>-->
                <div class="postDetails">
                    <?php if ($this->getCommentsEnabled()): ?>
                    <?php endif; ?>
                    <?php $postCats = $post->getCats(); ?>
                    <?php if (!empty($postCats)): ?>
                        <!--                    --><?php //echo Mage::helper('blog')->__('Posted in'); ?>
                        <?php foreach ($postCats as $data): ?>
                            <!--                        <a href="--><?php //echo $data['url']; ?><!--">--><?php //echo $data['title']; ?><!--</a>-->
                        <?php endforeach; ?>
                    <?php else: ?>

                    <p class="blue_name"><?php endif; ?><?php echo $post->getUser(); ?></p>
                    <h3><?php echo $post->getCreatedTime(); ?></h3>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
    <!-- --><?php //echo $this->getChildHtml('blog_comments_toolbar'); ?>
<?php else: ?>
    <?php echo Mage::helper('blog')->__('No Posts in this Category.'); ?>
<?php endif; ?>