<div class="block block-blog">
    <div class="block-title">
        <strong><span><?php echo Mage::getStoreConfig('blog/blog/title'); ?></span></strong>
    </div>
    <div class="block-content">
        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="menu-categories">
                <h5><?php echo Mage::helper('blog')->__('Categories'); ?></h5>
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>"><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <h5><?php echo Mage::helper('blog')->__('Last Posts'); ?></h5>
        <?php if ($posts = $this->getRecent()): ?>
            <div class="menu-recent">
                <h5><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h5>
                <ul>
                    <?php foreach ($posts as $post): ?>
                        <li><a href="<?php echo $post->getAddress(); ?>"><?php echo $post->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php echo $this->getChildHtml('blog_tags'); ?>
    </div>
</div>

<?php $comments = $this->getSidebarComments(); ?>

<?php foreach ($comments as $comment) : ?>

    <div class="sidebar_comments row">
        <div class="col-lg-4 sidebar">

            <a href="<?php echo(Mage::getUrl('blog') . $comment->getIdentifier()); ?> "><img
                    src="<?php echo(Mage::getBaseUrl('media') . $comment->getImage()); ?>"></a>

        </div>

        <div class="col-lg-8 sidebar">
            <p class="blue_name"><?php echo $comment->getUser() ?></p>

            <?php $date = $comment->getCreatedTime();
            $dateToShow = date('j F Y',strtotime($date)); ?>

            <h6 class=""><?php echo $dateToShow; ?></h6>
            <p><?php echo $comment->getComment(); ?></p>
        </div>

    </div>
    <hr>
<?php endforeach; ?>