<h4><?php echo $this->__('Products'); ?>:</h4>

<ol class="products-list" id="products-list">
    <?php foreach ($this->getProducts() as $_product): ?>

    <?php $amazonAttributes = json_decode($_product->getData('amazon_attributes'), true); ?>

    <li class="item">

        <a class="view-detail" <?php if (Mage::getStoreConfig('quickview/general/enabled')): ?> id='fancybox<?php echo $_product->getId() ?>'  href="<?php echo $this->getUrl('quickview/index/ajax', array('product_id' => $_product->getId())); ?>"<?php else: ?> href="<?php echo $_product->getProductUrl() ?>" href="<?php echo $_product->getProductUrl() ?>" <?php endif ?>
           title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><i
                    class="fa fa-search"></i></a>

        <div class="row">
            <div class="product-images col-sm-3 col-md-3 col-sms-6 col-smb-12">
                <div class="box-images">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                       class="product-image">
                        <?php $imagehv = $_product->load('media_gallery')->getMediaGalleryImages()->getItemByColumnValue('position', '2');
                        if ($imagehv) : $imagehv = $imagehv->getFile();
                            ?>
                            <img class="img-face-back"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $imagehv)->resize(200, 200) ?>"
                                 alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                        <?php endif ?>
                        <img class="img-face"
                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200, 200); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
                </div>
            </div>
            <div class="product-shop col-sm-9 col-md-9 col-sms-6 col-smb-12">

                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                <h2 class="product-name">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $_productNameStripped; ?>">
                        <?php echo $_product->getName(); ?></a>
                </h2>

                <?php echo Mage::helper('amazonia')->renderRating($_product); ?>
                <?php echo Mage::helper('amazonia')->renderPrice($_product); ?>

                <div class="actions">
                    <a class="button default" href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->__('View Details'); ?>
                    </a>
                    <?php if (!empty($amazonAttributes['DetailPageURL'])): ?>
                        <a class="button add-to-cart" target="_blank"
                           href="<?php echo $amazonAttributes['DetailPageURL']; ?>">
                            <?php echo $this->__('Zum Artikel'); ?>
                        </a>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </li>
<?php endforeach; ?>
</ol>
