<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Cart/SettingsInterface.php
 */

interface Brontosoftware_Magento_Cart_SettingsInterface extends Brontosoftware_Magento_Integration_CartSettingsInterface, Brontosoftware_Magento_Connector_Event_HelperInterface
{
    const XML_PATH_API_TOGGLE = 'brontosoftware/integration/extensions/cart_recovery/toggle_api';
    const XML_PATH_RECOVERY_EMAIL = 'brontosoftware/integration/extensions/cart_recovery/selectors';

    /**
     * Determines if the user turned on REST API integration or not
     *
     * @param string $scope
     * @param mixed $scopeId
     * @return boolean
     */
    public function isToggled($scope = 'default', $scopeId = null);

    /**
     * Gets the CSS selectors used to observe for guest abandons
     *
     * @param string $scope
     * @param mixed $scopeId
     * @return string
     */
    public function getCartRecoverySelectors($scope = 'default', $scopeId = null);

    /**
     * Encodes and encrypts the email value for cookie storage
     *
     * @param string $email
     * @return string
     */
    public function setCartRecoveryCookie($email);
}
