<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/App/EmulationInterface.php
 */

interface Brontosoftware_Magento_Core_App_EmulationInterface
{
    /**
     * Starts an emulated environment for the store in the area
     *
     * @param mixed $storeId
     * @param string $area
     * @param boolean $force
     * @return void
     */
    public function startEnvironmentEmulation($storeId, $area, $force);

    /**
     * Stops any running emulated environment
     *
     * @return void
     */
    public function stopEnvironmentEmulation();
}
