<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Sales/AddressRenderInterface.php
 */

interface Brontosoftware_Magento_Core_Sales_AddressRenderInterface
{
    /**
     * Takes an address model and formats to the specified type
     *
     * @param mixed $address
     * @param string $type
     * @return string
     */
    public function format($address, $type);
}
