<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Sales/CheckoutSessionInterface.php
 */

interface Brontosoftware_Magento_Core_Sales_CheckoutSessionInterface
{
    /**
     * Gets a Magento cart already initialized and reset
     *
     * @return mixed
     */
    public function getInitializedCart();

    /**
     * Gets a cart from the session, or creates an empty one
     *
     * @return mixed
     */
    public function getQuote();

    /**
     * Attempts to pull a quoteId off the session
     *
     * @return mixed
     */
    public function getQuoteId();

    /**
     * Resets the the checkout session
     *
     * @return void
     */
    public function resetCheckout();
}
