<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Sales/OrderCacheInterface.php
 */

interface Brontosoftware_Magento_Core_Sales_OrderCacheInterface
{
    /**
     * Gets an order by its unique id
     *
     * @param mixed $orderId
     * @return mixed
     */
    public function getById($orderId);
}
