<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Sales/QuoteManagementInterface.php
 */

interface Brontosoftware_Magento_Core_Sales_QuoteManagementInterface
{
    /**
     * Assign a cart to a customer in a given store
     *
     * @param mixed $quoteId
     * @param mixed $customerId
     * @param mixed $storeId
     * @return mixed
     */
    public function assignCustomer($quoteId, $customerId, $storeId);

    /**
     * Provided there's a customer ID, load an active cart
     *
     * @param mixed $customerId
     * @return mixed
     */
    public function getCartForCustomer($customerId);

    /**
     * Gets a cart by ID
     *
     * @param mixed $quoteId
     * @return mixed
     */
    public function getById($quoteId);
}
