<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Email/FilterEventInterface.php
 */

interface Brontosoftware_Magento_Email_FilterEventInterface
{
    /**
     * Implementors will add Bronto tags $name => $content
     *
     * @param array $message
     * @param array $templateVars
     * @param boolean $forceContext
     * @return array
     */
    public function apply($message, $templateVars = array(), $forceContext);
}
