<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Email/TemplateFilterInterface.php
 */

interface Brontosoftware_Magento_Email_TemplateFilterInterface
{
    /**
     * Sets any variables on the template
     *
     * @param array $templateVars
     * @return $this
     */
    public function setVariables($templateVars = array());

    /**
     * Adds a filter event listener to the template filter
     *
     * @param Brontosoftware_Magento_Email_FilterEventInterface $filter
     * @return $this
     */
    public function addEventFilter(Brontosoftware_Magento_Email_FilterEventInterface $filter);

    /**
     * Gets a key => value pair context derived
     *
     * @param array $message
     * @param boolean $forceContext
     * @return array
     */
    public function getContext($message, $forceContext = true);

    /**
     * Gets a list of replaced tags in the template
     *
     * @return array
     */
    public function getReplacedTags();

    /**
     * Transforms the context into Bronto API tags
     *
     * @param array $message
     * @return array
     */
    public function applyAndTransform($message);
}
