<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Email/TriggerManagerInterface.php
 */

interface Brontosoftware_Magento_Email_TriggerManagerInterface
{
    const LIMIT = 25;
    const DAYS_THRESHOLD = 30;

    /**
     * Determines if there are any messages in the trigger queue
     *
     * @param string $siteId
     * @return bool
     */
    public function hasItems($siteId);

    /**
     * Writes a trigger to the queue
     *
     * @param Brontosoftware_Magento_Email_TriggerInterface $trigger
     * @return Brontosoftware_Magento_Email_TriggerInterface
     */
    public function save(Brontosoftware_Magento_Email_TriggerInterface $trigger);

    /**
     * Returns a collection of all recorded triggers for
     * the provided model
     *
     * @param string $siteId
     * @param string $modelType
     * @param mixed $modelId
     * @return mixed
     */
    public function getTriggers($siteId, $modelType, $modelId);

    /**
     * Creates a new trigger with the given type
     *
     * @param string $siteId
     * @param string $messageType
     * @param string $messageId
     * @return Brontosoftware_Magento_Email_TriggerInterface
     */
    public function createTrigger($siteId, $messageType, $messageId);

    /**
     * Gets all of the triggers ready to be sent
     *
     * @param string $siteId
     * @param mixed $customerEmail
     * @param int $limit
     * @param string $messageType
     * @return mixed
     */
    public function getApplicableTriggers($siteId, $customerEmail = null, $limit = null, $messageType = null);

    /**
     * Deletes the trigger from the queue
     *
     * @param Brontosoftware_Magento_Email_TriggerInterface $trigger
     * @return void
     */
    public function delete(Brontosoftware_Magento_Email_TriggerInterface $trigger);


    /**
     * Deletes the trigger entries from the queue older than this date
     *
     * @param string $siteId
     * @param int $daysInthePast
     * @return void
     */
    public function deleteExpiredItems($siteId, $daysInthePast = null);

    /**
     * Creates an event source for the message and message type
     *
     * @param Brontosoftware_Magento_Email_TriggerInterface $trigger
     * @param array $message
     * @return Brontosoftware_Magento_Connector_Event_SourceInterface
     */
    public function createSource($trigger, $message);
}
