<?php
$attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'manufacturer');
$manufacturers = $attribute->getSource()->getAllOptions();
?>

<section class="brandlogo-wrapper">
    <div class="brandlogo-contain">

        <div class="bx-title brand-title"><h2><?php echo $this->__('Brand & Cliens') ?></h2></div>
        <ul class="bxslider">

            <?php foreach ($manufacturers as $option) : ?>
                <?php $brandImage = Mage::helper('attributeimage')->getAttributeImage($option['value']); ?>
                    <li class="item">
                        <div class="brand_block">
                            <?php if ($brandImage): ?>
                                <a href="#" title=""><img class="brand_image" src="<?php echo $brandImage; ?>"/></a>
                            <?php else : ?>
                                <h3 class="brand_label"><?php echo $option['label']; ?></h3>
                            <?php endif; ?>
                        </div>
                    </li>
            <?php endforeach; ?>

        </ul>

        <script type="text/javascript">
            //<![CDATA[
            jQuery(document).ready(function ($) {
                $('.brandlogo-contain .bxslider').bxSlider(
                    {
                        <?php if($this->getConfig('auto')) { ?>
                        auto: true,
                        <?php } ?>
                        speed: <?php echo $this->getConfig('speed') ?>,
                        pause: <?php echo $this->getConfig('interval') ?>,
                        minSlides: 1,
                        //infiniteLoop: false,
                        maxSlides: <?php echo $this->getConfig('items_show') ?>,
                        slideWidth: <?php echo $this->getConfig('item_width') ?>,
                        slideMargin: 5,
                        autoHover: true,
                        moveSlides: 1,
                        <?php if ($this->getConfig('nav_ctrl')) { ?>
                        pager: true,
                        <?php } else { ?>
                        pager: false,
                        <?php } ?>
                        <?php if ($this->getConfig('next_back')) { ?>
                        controls: true,
                        <?php } else { ?>
                        controls: false,
                        <?php } ?>
                    }
                );
            });
            //]]>
        </script>
    </div>
</section>

