<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery/AdvancedExtensionInterface.php
 */

interface Brontosoftware_Magento_Connector_Discovery_AdvancedExtensionInterface extends Brontosoftware_Magento_Connector_Discovery_ExtensionInterface
{
    /**
     * Observe the discovery builder advanced endpoint to
     * enhance Advanced options
     *
     * @param mixed $observer
     * @return void
     */
    public function advancedAdditional($observer);
}
