<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery/ExtensionInterface.php
 */

interface Brontosoftware_Magento_Connector_Discovery_ExtensionInterface extends Brontosoftware_Magento_Connector_Discovery_TranslationInterface
{
    /**
     * Observe the discovery builder to create extension definition
     *
     * @param mixed $observer
     * @return void
     */
    public function gatherEndpoints($observer);

    /**
     * Observe the endpoint callback to create endpoint definition
     *
     * @param mixed $observer
     * @return void
     */
    public function endpointInfo($observer);
}
