<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery/PushChangesInterface.php
 */

interface Brontosoftware_Magento_Connector_Discovery_PushChangesInterface
{
    /**
     * This extension will push object changes that match an event type
     *
     * @param mixed $observer
     * @return void
     */
    public function pushChanges($observer);
}
