<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery/Source.php
 */

class Brontosoftware_Magento_Connector_Discovery_Source
{
    protected $_registration;
    protected $_page = 0;
    protected $_perPage = 20;
    protected $_scopeHash;
    protected $_uniqueId = false;
    protected $_filters = array();
    protected $_results = array();

    /**
     * @param Brontosoftware_Magento_Connector_RegistrationInterface $registration
     */
    public function __construct(Brontosoftware_Magento_Connector_RegistrationInterface $registration)
    {
        $this->_registration = $registration;
    }

    /**
     * Sets the request params from the request
     *
     * @param array $params
     * @return $this
     */
    public function setParams(array $params = array())
    {
        foreach ($params as $key => $values) {
            list($value) = $values;
            switch ($key) {
                case 'page':
                    $this->_page = $value;
                    break;
                case 'perPage':
                    $this->_perPage = $value;
                    break;
                case 'scopeId':
                    $this->_scopeHash = $value;
                    break;
                case 'id':
                    $this->_uniqueId = $value;
                    break;
                default:
                    $this->_filters[$key] = $value;
                    break;
            }
        }
        return $this;
    }

    /**
     * Gets the filters from the request
     *
     * @return array
     */
    public function getFilters()
    {
        return $this->_filters;
    }

    /**
     * Gets the limit param from the request
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->_perPage;
    }

    /**
     * Gets the offset param from the request
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->_page * $this->_perPage;
    }

    /**
     * Retrieves the current page from the request
     *
     * @return int
     */
    public function getCurrentPage()
    {
        return $this->_page;
    }

    /**
     * Sets the computed results provided by the source handler
     *
     * @param array $results
     * @return $this
     */
    public function setResults(array $results = array())
    {
        $this->_results = $results;
        return $this;
    }

    /**
     * Retrieves a collection of results from the source handler
     *
     * @return array
     */
    public function getResults()
    {
        return $this->_results;
    }

    /**
     * Retrieves the source scope hash for the source, if applicable
     *
     * @return string
     */
    public function getScopeHash()
    {
        if (is_null($this->_scopeHash)) {
            return $this->getRegistration()->getScopeHash();
        } else {
            return $this->_scopeHash;
        }
    }

    /**
     * Gets the registration that belongs to the request
     *
     * @return Brontosoftware_Magento_Connector_RegistrationInterface
     */
    public function getRegistration()
    {
        return $this->_registration;
    }

    /**
     * Gets the unique identifier value for the source
     *
     * @return mixed
     */
    public function getId()
    {
        return $this->_uniqueId;
    }
}
