<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery/TranslationInterface.php
 */

interface Brontosoftware_Magento_Connector_Discovery_TranslationInterface
{
    /**
     * Performs a translation on any string
     *
     * @param string $string
     * @return string
     */
    public function translate($string);
}
