<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Product/CatalogMapperManagerInterface.php
 */

interface Brontosoftware_Magento_Product_CatalogMapperManagerInterface
{
    /**
     * Gets some external object containing fields
     *
     * @return mixed
     */
    public function getByProduct($product);
}
