<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Product/CatalogMapperAbstract.php
 */

abstract class Brontosoftware_Magento_Product_CatalogMapperAbstract implements Brontosoftware_Magento_Product_CatalogMapperInterface
{
    protected $_manager;

    /**
     * @param Brontosoftware_Magento_Product_CatalogMapperManagerInterface $manager
     */
    public function __construct(Brontosoftware_Magento_Product_CatalogMapperManagerInterface $manager)
    {
        $this->_manager = $manager;
    }

    /**
     * Gets a hashmap of applicable codes
     *
     * @return array
     */
    public abstract function getExtraFields();

    /**
     * Gets a hashmap of mapped default Fields
     *
     * @return array
     */
    public abstract function getDefaultFields();

    /**
     * Gets a collection of attribute objects
     *
     * @return array
     */
    public abstract function getFieldAttributes();

    /**
     * Determines if the mappings contains applicable codes
     *
     * @param array $mappings
     * @return boolean
     */
    public function isApplicableCodes($mappings)
    {
        foreach ($this->getExtraFields() as $code => $fieldLabel) {
            if (array_key_exists($code, $mappings)) {
                return true;
            }
        }
        return false;
    }

    /**
     * @see parent
     */
    public function setExtraFields($observer)
    {
        $product = $observer->getProduct();
        $mappings = $observer->getMappings();
        $container = $observer->getContainer();
        if ($this->isApplicableCodes($mappings)) {
            $extra = $container->getFields();
            $object = $this->_manager->getByProduct($product);
            foreach ($this->getExtraFields() as $code => $fieldLabel) {
                $extra[$code] = $object->getData($code);
            }
            $container->setFields($extra);
        }
    }

    /**
     * @see parent
     */
    public function setDefaultFields($observer)
    {
        $fields = $observer->getContainer()->getFields();
        $allCodes = $this->getExtraFields();
        foreach ($this->getDefaultFields() as $defaultId => $fieldId) {
            $fields[$defaultId] = array($fieldId => $allCodes[$fieldId]);
        }
        $observer->getContainer()->setFields($fields);
    }

    /**
     * @see parent
     */
    public function setCustomFields($observer)
    {
        $fields = $observer->getContainer()->getFields();
        foreach ($this->getExtraFields() as $id => $name) {
            $fields[] = array('id' => $id, 'name' => $name);
        }
        $observer->getContainer()->setFields($fields);
    }

    /**
     * @see parent
     */
    public function setFieldAttributes($observer)
    {
        $fields = $observer->getContainer()->getFields();
        $allCodes = $this->getExtraFields();
        foreach ($this->getFieldAttributes() as $code => $type) {
            if (array_key_exists($code, $allCodes)) {
                $fields[] = array(
                    'attribute_code' => $code,
                    'frontend_label' => $allCodes[$code],
                    'frontend_type' => $type,
                    'is_global' => true
                );
            }
        }
        $observer->getContainer()->setFields($fields);
    }
}
