<?php
/** @var Colibo_Similarproducts_Block_Productlist $this */

/** @var Mage_Catalog_Model_Resource_Product_Collection $products */
$products = $this->getSimilarProducts();

if (count($products)) {
    ?>

    <div class="colibo-similarproducts">
        <ol class="products-list" id="products-list">
            <?php

            $helper = $this->helper('catalog/output');

            /** @var Mage_Catalog_Model_Product $product */
            foreach ($products as $product) {
                $img = '<img src="' . $this->helper('catalog/image')->init($product, 'small_image')->resize(165) . '" alt="' . $this->escapeHtml($this->getImageLabel($product)) . '" title="' . $this->escapeHtml($this->getImageLabel($product)) . '" />';
                ?>
                <li class='item similarproducts-item'>
                    <a class="view-detail" <?php if (Mage::getStoreConfig('quickview/general/enabled')): ?> id='fancybox<?php echo $product->getId() ?>'  href="<?php echo $this->getUrl('quickview/index/ajax', array('product_id' => $product->getId())); ?>"<?php else: ?> href="<?php echo $product->getProductUrl() ?>"<?php endif ?>
                       title="<?php echo $this->stripTags($product->getName(), null, true) ?>"><i
                            class="fa fa-search"></i></a>
                    <a href='<?php echo $product->getProductUrl(); ?>'><?php echo $helper->productAttribute($product, $img, 'image') ?></a>
                </li>
                <?php
            }
            ?>
        </ol>
    </div>
<?php } ?>



