<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Optin/Checkout.php
 */

class Brontosoftware_Magento_Optin_Checkout
{
    protected $_settings;
    protected $_subscribers;

    /**
     * @param Brontosoftware_Magento_Optin_SettingsInterface $settings
     * @param Brontosoftware_Magento_Core_Subscriber_ManagerInterface $subscribers
     */
    public function __construct(
        Brontosoftware_Magento_Optin_SettingsInterface $settings,
        Brontosoftware_Magento_Core_Subscriber_ManagerInterface $subscribers
    ) {
        $this->_settings = $settings;
        $this->_subscribers = $subscribers;
    }

    /**
     * Determines if the checkbox should be shown using basic logic
     *
     * @param mixed $storeId
     * @param mixed $customer
     * @param string $area
     * @return boolean
     */
    public function isCheckboxVisible($storeId, $customer = null, $area = null)
    {
        if (!$this->_settings->isCheckoutEnabled('store', $storeId)) {
            return false;
        }

        if (!is_null($customer)) {
            $subscriber = $this->_subscribers->getByEmail($customer->getEmail());
            if ($subscriber && $subscriber->getSubscriberStatus() == 1) {
                return false;
            }
        }

        if (is_null($area)) {
            return true;
        } else {
            $selectedArea = $this->_settings->getCheckoutLayout('store', $storeId);
            return $selectedArea == $area;
        }
    }

    /**
     * Determines if the checkbox on checkout is checked by default
     *
     * @param mixed $storeId
     * @return boolean
     */
    public function isCheckboxChecked($storeId)
    {
        return $this->_settings->isCheckedByDefault('store', $storeId);
    }
}
