<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Notification/ManagerInterface.php
 */

interface Brontosoftware_Magento_Notification_ManagerInterface
{
    /**
     * Creates announcements within the platform
     *
     * @param array $items
     * @return array
     */
    public function createAnnouncements($items);

    /**
     * Marks item as read
     *
     * @param mixed $notificationId
     * @return void
     */
    public function markAsRead($notificationId);
}
