<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Notification/Manager.php
 */

class Brontosoftware_Magento_Notification_Manager implements Brontosoftware_Magento_Notification_ManagerInterface
{
    const TYPE_GENERAL = 'general';
    const TYPE_RELEASE = 'release';

    protected $_inbox;

    /**
     * @param Brontosoftware_Magento_Core_Notification_InboxInterface $inbox
     */
    public function __construct(
        Brontosoftware_Magento_Core_Notification_InboxInterface $inbox
    ) {
        $this->_inbox = $inbox;
    }

    /**
     * @see parent
     */
    public function createAnnouncements($items)
    {
        $results = array();
        foreach ($items as $item) {
            if ($this->_createNotification($item)) {
                $results[] = $item['id'];
            }
        }
        return $results;
    }

    /**
     * @see parent
     */
    public function markAsRead($notificationId)
    {
        $this->_inbox->markAsRead($notificationId);
    }

    /**
     * Determines if this alert should be written in the platform
     *
     * @param array $item
     * @return boolean
     */
    protected function _isAlert($item)
    {
        return (
            $item['type'] != self::TYPE_GENERAL ||
            preg_match('/^\[?ALERT\]?/i', $item['title'])
        );
    }

    /**
     * Writes this notification as an admin notice
     *
     * @param array $item
     * @return boolean
     */
    protected function _createNotification($item)
    {
        if ($this->_isAlert($item)) {
            $title = "[Bronto Notification] {$item['title']}";
            return $this->_inbox->addNotice($title, $item['description'], $item['url']);
        }
        return true;
    }
}
