<?php if (Mage::getStoreConfig('quickview/general/enabled')): ?>
    <?php $_helper = $this->helper('catalog/output'); ?>
    <?php $_product = $this->getProduct(); ?>
    <?php $amazonAttributes = json_decode($_product->getData('amazon_attributes'), true); ?>

    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

    <div class="product-view">
        <div class="product-essential">

            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post"
                  id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="row">

                    <div class="product-img-box col-sm-5 col-md-5">
                        <?php echo $this->getChildHtml('media') ?>
                    </div>

                    <div class="product-shop col-sm-7 col-md-7">

                        <div class="product-name">
                            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                        </div>

                        <div class="ratings">
                            <div class="rating-box">
                                <div class="rating"
                                     style="width:<?php echo ($_product->getRating() / 5) * 100 ?>%"></div>
                            </div>
                        </div>

                        <p class="availability
                            <?php if ($_product->getPrice() != 0.00 && $_product->getPriceUsed() != 0.00): ?>
                                in-stock
                            <?php else: ?>
                                out-of-stock
                            <?php endif; ?>">
                            Availability:
                            <?php if ($_product->getPrice() != 0.00 && $_product->getPriceUsed() != 0.00): ?>
                                <span>In stock</span>
                            <?php else: ?>
                                <span>Out of stock</span>
                            <?php endif; ?>
                        </p>

                        <ul>
                            <li class="asin">
                                ASIN:
                                <strong><?php echo $this->getProduct()->getData('sku'); ?></strong>
                            </li>
                        </ul>

                        <!--<dt>Brand:</dt>
                    <dd><?php /*echo $this->getProduct()->getAttributeText('manufacturer'); */ ?></dd>

                    <dt class="asin">Model:</dt>
                    <dd><?php /*echo $this->getProduct()->getData('model'); */ ?></dd>

                    <dt>Color:</dt>
                    <dd><?php /*echo $this->getProduct()->getAttributeText('color'); */ ?></dd>

                    <dt>EAN:</dt>
                    <dd><?php /*echo $this->getProduct()->getData('ean'); */ ?></dd>

                    <dt>Weight:</dt>
                    <dd><?php /*echo number_format($this->getProduct()->getData('weight'), 2, ',', ''); */ ?>kg.</dd>-->

                        <div class="add-to-box">

                            <?php if ($_product->getPrice() > 0) : ?>
                                <span class="price-box row">
                                    <span class="price-label col-md-4 new">Lowest New Price:</span>
                                    <span class="price col-md-8">
                                        <span class="col-md-8">
                                              <?php echo Mage::helper('core')->currency($_product->getPrice(), true, false); ?>
                                        </span>
                                        <span class="total-count col-md-4 text-right">
                                           <?php if (!empty($_product->getOffersNumberNew())) : ?>
                                               <?php echo $_product->getOffersNumberNew(); ?> items
                                           <?php endif; ?>
                                        </span>
                                    </span>
                                </span>
                            <?php endif; ?>

                            <?php if ($_product->getPriceUsed() > 0) : ?>
                                <span class="price-box row">
                                    <span class="price-label col-md-4 used">Lowest Used Price:</span>
                                    <span class="price col-md-8">
                                        <span class="col-md-8">
                                             <?php echo Mage::helper('core')->currency($_product->getPriceUsed(), true, false); ?>
                                        </span>
                                        <span class="total-count col-md-4 text-right">
                                            <?php if (!empty($_product->getOffersNumberUsed())) : ?>
                                                <?php echo $_product->getOffersNumberUsed(); ?> items
                                            <?php endif; ?>
                                        </span>
                                    </span>
                                </span>
                            <?php endif; ?>

                            <?php if (!empty($amazonAttributes['DetailPageURL'])): ?>
                                <div class="row">
                                    <br>
                                    <a class="col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 button add-to-cart"
                                       target="_blank"
                                       href="<?php echo $amazonAttributes['DetailPageURL']; ?>">
                                        <?php echo $this->__('Zum Shop'); ?>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>
                </div>
                <div class="clearer"></div>

            </form>

            <div class="product-collateral row-fluid">
                <?php echo $this->getChildHtml('info_tabs') ?>
                <?php echo $this->getChildHtml('upsell_products') ?>
                <?php echo $this->getChildHtml('product_additional_data') ?>
            </div>

            <script type="text/javascript">
                jQuery('.cloud-zoom, .cloud-zoom-gallery').CloudZoom();
            </script>

        </div>

    </div>
<?php endif; ?>