<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Config/ScopedInterface.php
 */

interface Brontosoftware_Magento_Core_Config_ScopedInterface
{
    /**
     * Gets a value store in the system config for a scope
     *
     * @param string $path
     * @param string $scopeName
     * @param mixed $scopeId
     * @return string
     */
    public function getValue($path, $scopeName = 'default', $scopeId = null);

    /**
     * Gets a stored flag in the system config for a scope
     *
     * @param string $path
     * @param string $scopeName
     * @param mixed $scopeId
     * @return boolean
     */
    public function isSetFlag($path, $scopeName = 'default', $scopeId = null);
}
