<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Email/Event/Trigger/Caretip.php
 */

class Brontosoftware_Magento_Email_Event_Trigger_Caretip extends Brontosoftware_Magento_Email_Event_Trigger_OrderBasedAbstract
{
    /**
     * @see parent
     */
    public function transform($lineItem)
    {
        $order = $lineItem->getOrder();
        $store = $order->getStore();
        $inclTax = (int)$this->_config->getValue(self::XML_PATH_PRICE_DISPLAY, 'store', $store);
        $delivery = $this->_createDelivery($order->getCustomerEmail(), $store);
        $fields = array_merge(
            $this->_createOrderFields($order, $store),
            $this->_createLineItemFields($lineItem, $inclTax),
            $this->_extraFields(array('order' => $order)));
        $fields[] = $this->_createField('content', $this->_message['content']);
        $delivery['fields'] = $fields;
        return $delivery;
    }
}
