<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Email/Event/Trigger/Cart.php
 */

class Brontosoftware_Magento_Email_Event_Trigger_Cart extends Brontosoftware_Magento_Email_Event_Trigger_SourceAbstract
{
    const XML_PATH_PRICE_DISPLAY = 'tax/cart_display/price';
    const XML_PATH_SUBTOTAL_DISPLAY = 'tax/cart_display/subtotal';
    const XML_PATH_GRANDTOTAL_TAX = 'tax/cart_display/grandtotal';

    protected $_integration;

    /**
     * @param Brontosoftware_Magento_Integration_CartSettingsInterface $integration
     * @param Brontosoftware_Magento_Email_SettingsInterface $settings
     * @param Brontosoftware_Magento_Core_Directory_CurrencyManagerInterface $currencies
     * @param Brontosoftware_Magento_Email_TriggerInterface $trigger
     * @param Brontosoftware_Magento_Order_SettingsInterface $helper
     * @param Brontosoftware_Magento_Core_Config_ScopedInterface $config
     * @param array $message
     */
    public function __construct(
        Brontosoftware_Magento_Integration_CartSettingsInterface $integration,
        Brontosoftware_Magento_Email_SettingsInterface $settings,
        Brontosoftware_Magento_Core_Directory_CurrencyManagerInterface $currencies,
        Brontosoftware_Magento_Email_TriggerInterface $trigger,
        Brontosoftware_Magento_Order_SettingsInterface $helper,
        Brontosoftware_Magento_Core_Config_ScopedInterface $config,
        array $message
    ) {
        parent::__construct($settings, $currencies, $trigger, $helper, $config, $message);
        $this->_integration = $integration;
    }

    /**
     * @see parent
     */
    public function action($quote)
    {
        $originalAction = parent::action($quote);
        if ($quote->getIsActive() == 0 || $quote->getReservedOrderId()) {
            return '';
        }
        return $originalAction;
    }

    /**
     * @see parent
     */
    public function transform($quote)
    {
        $store = $quote->getStore();
        $delivery = $this->_createDelivery($this->_trigger->getCustomerEmail(), $store,
            !isset($this->_message['previousMessage']) ?
                $this->_message['sendType'] :
                'triggered');
        $fields = $this->_extraFields(array('quote' => $quote));
        $subtotalDisplay = (int)$this->_config->getValue(self::XML_PATH_SUBTOTAL_DISPLAY, 'store', $store);
        $this->_setCurrency($quote->getQuoteCurrencyCode());
        $fields[] = $this->_createField('subtotal', $this->_formatPrice($quote->getSubtotal()));
        $fields[] = $this->_createField('subtotalExclTax', $this->_formatPrice($quote->getSubtotal()));
        if ($subtotalDisplay != 1) {
            $totals = $quote->getTotals();
            $fields[] = $this->_createField('subtotalInclTax', $this->_formatPrice($totals['subtotal']->getValue()));
        } else {
            $fields[] = $this->_createField('subtotalInclTax', $this->_formatPrice($quote->getSubtotal()));
        }
        if ($this->_config->isSetFlag(self::XML_PATH_GRANDTOTAL_TAX, 'store', $store)) {
            $totals = $quote->getTotals();
            $fields[] = $this->_createField('grandTotal', $this->_formatPrice($totals['grand_total']->getValue()));
        } else {
            $fields[] = $this->_createField('grandTotal', $this->_formatPrice($quote->getGrandTotal()));
        }
        $index = 1;
        $inclTax = (int)$this->_config->getValue(self::XML_PATH_PRICE_DISPLAY, 'store', $store);
        foreach ($this->_helper->getFlatItems($quote) as $lineItem) {
            $fields = array_merge($fields, $this->_createLineItemFields($lineItem, $inclTax, $index));
            $index++;
        }
        $fields[] = $this->_createField('quoteURL', $this->_integration->getRedirectUrl($quote->getId(), $store));
        $delivery['fields'] = $fields;
        return $delivery;
    }
}
