<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Discovery.php
 */


class Brontosoftware_Magento_Connector_Discovery
{
    private $_increment = 1;
    private $_groups = array();

    /**
     * Add a group object to the discovery document
     *
     * @param array $group
     * @return $this
     */
    public function addGroup(array $group)
    {
        if (!array_key_exists('sort_order', $group)) {
            $wrapped = array(
                'definition' => $group,
                'sort_order' => $this->_increment++
            );
            $group = $wrapped;
        }
        $this->_groups[] = $group;
        return $this;
    }

    /**
     * Add a an extension group from a Brontosoftware_Magento_Connector_Discovery_GroupInterface
     *
     * @param Brontosoftware_Connector_Model_Discovery_GroupInterface $group
     * @return $this
     */
    public function addGroupHelper(Brontosoftware_Magento_Connector_Discovery_GroupInterface $group)
    {
        return $this->addGroup(array(
            'sort_order' => $group->getSortOrder(),
            'definition' => array(
                'id' => $group->getEndpointId(),
                'name' => $group->getEndpointName(),
                'icon' => $group->getEndpointIcon()
            )
        ));
    }

    /**
     * Gets the extension group objects for the discovery document
     *
     * @return array
     */
    public function getGroups()
    {
        return $this->_groups;
    }
}
