<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/QueueManagerInterface.php
 */

interface Brontosoftware_Magento_Connector_QueueManagerInterface
{
    const LIMIT = 25;

    /**
     * Determines if there are any entries in the queue
     *
     * @param string $siteId
     * @return bool
     */
    public function hasItems($siteId);

    /**
     * Writes an event to the queue
     *
     * @param array $event
     * @return bool
     */
    public function save($event);

    /**
     * Gets the oldest events to flush from the manager
     *
     * @param string $siteId
     * @param int $limit
     * @param string $type
     * @return Iterator
     */
    public function getOldestEvents($siteId, $limit = null, $type = null);

    /**
     * Directly deletes the queue entry
     *
     * @param Brontosoftware_Magento_Connector_QueueInterface $queue
     * @return void
     */
    public function delete(Brontosoftware_Magento_Connector_QueueInterface $queue);

    /**
     * Deletes any queue entries by these ids
     *
     * @param array $queueIds
     * @return void
     */
    public function deleteByIds(array $queueIds);
}
