<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Connector/Settings.php
 */

class Brontosoftware_Magento_Connector_Settings extends Brontosoftware_Magento_Core_Config_ContainerAbstract implements Brontosoftware_Magento_Connector_SettingsInterface
{
    /**
     * @see parent
     */
    public function getSiteId($scope = 'default', $scopeId = null)
    {
        return $this->_config->getValue(self::XML_PATH_SITEID, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function getMaskId($scope = 'default', $scopeId = null)
    {
        return $this->_config->getValue(self::XML_PATH_MASKID, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function isOrderService($scope = 'default', $scopeId = null)
    {
        return $this->_config->isSetFlag(self::XML_PATH_ORDER_SERVICE, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function isToggled($endpointId, $scope = 'default', $scopeId = null)
    {
        $path = sprintf(self::XML_PATH_TOGGLE_PREFIX, $endpointId);
        return $this->_config->isSetFlag($path, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function isTestMode($scope = 'default', $scopeId = null)
    {
        return $this->_config->isSetFlag(self::XML_PATH_TEST_MODE, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function isFlushDisabled($scope = 'default', $scopeId = null)
    {
        return $this->_config->isSetFlag(self::XML_PATH_DISABLE_FLUSH, $scope, $scopeId);
    }

    /**
     * @see parent
     */
    public function isEventQueued($scope = 'default', $scopeId = null)
    {
        return true;
    }
}
