<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/MetaInterface.php
 */

interface Brontosoftware_Magento_Core_MetaInterface
{
    const PLATFORM_ID = 'magento';

    /**
     * Gets the platform name
     *
     * @return string
     */
    public function getName();

    /**
     * Gets the platform version
     *
     * @return string
     */
    public function getVersion();

    /**
     * Gets the platform edition
     *
     * @return string
     */
    public function getEdition();

    /**
     * Gets the extension version
     *
     * @return string
     */
    public function getExtensionVersion();

    /**
     * Gets the admin frontend Name
     *
     * @return string
     */
    public function getAdminFrontName();
}
