<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Contact/AttributeExtensionAbstract.php
 */

abstract class Brontosoftware_Magento_Contact_AttributeExtensionAbstract implements Brontosoftware_Magento_Contact_AttributeExtensionInterface
{
    protected $_settings;

    /**
     * @param Brontosoftware_Magento_Contact_AttributeSettingsInterface $settings
     */
    public function __construct(
        Brontosoftware_Magento_Contact_AttributeSettingsInterface $settings
    ) {
        $this->_settings = $settings;
    }

    /**
     * @see parent
     */
    public function contactAdditional($observer)
    {
        foreach ($this->_settings->getFields() as $fieldId => $field) {
            $observer->getEndpoint()->addFieldToExtension($this->_defaultGroup(), array(
                'id' => $fieldId,
                'name' => $this->translate($field['name']),
                'type' => 'select',
                'typeProperties' => array(
                    'bronto' => array(
                        'type' => 'contactField',
                        'displayType' => $field['type']
                    )
                )
            ));
        }
    }

    /**
     * @see parent
     */
    public function contactLoadFields($observer)
    {
        $contact = $observer->getContact();
        $storeId = $observer->getStoreId();
        $container = $observer->getContainer();
        if ($this->_canMap($container->getAttributes())) {
            $extraFields = $this->_settings->getExtra($contact, $storeId);
            $container->setExtra($container->getExtra() + $extraFields);
        }
    }

    /**
     * Add the fields provided to the settings
     *
     * @return string
     */
    protected function _defaultGroup()
    {
        return 'attributes';
    }

    /**
     * Determines if a module setting is set in the settings
     *
     * @param array $attributes
     * @return boolean
     */
    protected function _canMap($attributes)
    {
        foreach ($this->_settings->getFields() as $fieldId => $field) {
            if (array_key_exists($fieldId, $attributes)) {
                return true;
            }
        }
        return false;
    }
}
