<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Contact/AttributeExtensionInterface.php
 */

interface Brontosoftware_Magento_Contact_AttributeExtensionInterface extends Brontosoftware_Magento_Connector_Discovery_TranslationInterface
{
    /**
     * Adds additional mappings to the customer attribute
     * section to send reward balance
     *
     * @param mixed $observer
     * @return void
     */
    public function contactAdditional($observer);

    /**
     * Loads the additional fields from the reward model
     *
     * @param mixed $observer
     * @return void
     */
    public function contactLoadFields($observer);
}
