<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Contact/SettingsInterface.php
 */

interface Brontosoftware_Magento_Contact_SettingsInterface extends Brontosoftware_Magento_Connector_Event_HelperInterface
{
    const XML_PATH_ENABLED = 'brontosoftware/contact/extensions/settings/enabled';
    const XML_PATH_SKIP_EMPTY = 'brontosoftware/contact/extensions/settings/skipEmpty';
    const XML_PATH_GUEST_ORDER = 'brontosoftware/contact/extensions/settings/guestOrder';

    /**
     * Determines wheter or not to skip empty field values
     *
     * @return boolean
     */
    public function isSkipEmpty($scopeType = 'default', $scopeId = null);

    /**
     * Gets the guest order contact field toggle
     *
     * @param string $scopeType
     * @param mixed $scopeId
     * @return string
     */
    public function getGuestOrderToggle($scopeType = 'default', $scopeId = null);

    /**
     * Gets the labels for the attribute sections
     *
     * @return array
     */
    public function getAttributeLabels();

    /**
     * Get the attribute filters
     *
     * @return array
     */
    public function getAttributeFilters();

    /**
     * Gets the attributes for the endpoint
     *
     * @return array
     */
    public function getAttributes();

    /**
     * Gets the attribute display type
     *
     * @param mixed $attribute
     * @return string
     */
    public function getAttributeDisplayType($attribute);

    /**
     * Gets the fields for a Magento model of some kind
     *
     * @param mixed $object
     * @param mixed $storeId
     * @param string $type
     * @return array
     */
    public function getFieldsForModel($object, $storeId, $type = 'contact');
}
