<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Serialize/BiDirectional.php
 */

/**
 * Interface that represents a complete bi-directional
 * serailizer with associated MIME type.
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
interface Brontosoftware_Serialize_BiDirectional extends Brontosoftware_Serialize_Encode, Brontosoftware_Serialize_Decode
{
    /**
     * Gets the MIME type for this bi-directional serializer
     *
     * @return string
     */
    public function getMimeType();
}
