<ul>
    <li class="row">
        <div class="col-md-2 text-center">ID</div>
        <div class="col-md-4">ASIN</div>
        <div class="col-md-4">Category</div>
        <div class="col-md-2"></div>
    </li>
    <?php foreach ($this->getJobs() as $job): ?>
        <li class="row">

            <form action="<?php echo $this->getUrl('amazon/adminhtml_magento/removejob/') ?>"
                  method="post">
                <input name="form_key" type="hidden"
                       value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                <input name="isAjax" type="hidden" value="true"/>
            </form>

            <div class="col-md-2 text-center">
                <?php echo $job['id']; ?>
            </div>
            <div class="col-md-4 job-asin">
                <?php echo $job['asin']; ?>
            </div>
            <div class="col-md-4">
                <?php echo $job['category']; ?>
            </div>
            <div class="col-md-2">
                <button class="remove-job btn btn-danger btn-xs">
                    <i class="fa fa-trash-o"></i>
                </button>
            </div>
        </li>
    <?php endforeach; ?>
</ul>