<div id="loader"></div>

<div id="amazon-products-import">


    <div class="content-header">
        <table cellspacing="0">
            <tbody>
            <tr>
                <td>
                    <h3 class="icon-head head-products">Amazon. Products Import</h3>
                </td>
            </tr>
            </tbody>
        </table>
    </div>


    <div class="col-md-12">
        <div class="row">

            <!-- Search Block -->
            <div class="col-md-6">
                <div class="panel block-eq panel-default">
                    <div class="panel-body panel-body-yellow">

                        <form action="<?php echo $this->getUrl('amazon/adminhtml_amazon/search/') ?>" method="post"
                              class="search-form">

                            <div class="row">
                                <dl class="dl-horizontal col-md-12">

                                    <dt>Keywords:</dt>
                                    <dd>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <input autofocus type="text" class="form-control" name="keywords"
                                                       placeholder="Keywords or direct ASIN ...">
                                            </div>
                                        </div>
                                    </dd>
                                    <dt>Search index:</dt>
                                    <dd>
                                        <div class="row">
                                            <div class="col-md-5">
                                                <select class="selectpicker" name="category">
                                                    <?php foreach ($this->getSearchIndexes() as $group => $options): ?>
                                                        <optgroup label="<?php echo $group; ?>">
                                                            <?php foreach ($options as $nodeId => $pair): ?>
                                                                <?php foreach ($pair as $code => $label): ?>
                                                                    <option value="<?php echo $code; ?>">
                                                                        <?php echo $label; ?>
                                                                    </option>
                                                                <?php endforeach; ?>
                                                            <?php endforeach; ?>
                                                        </optgroup>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                            <div class="col-md-7 text-right">
                                                <strong>Amazon nodes:</strong>
                                                <button type="button" class="btn btn-default" data-toggle="modal"
                                                        data-target="#treeModal">
                                                    <span>Please, select node ...</span>
                                                </button>
                                            </div>
                                        </div>
                                    </dd>
                                    <dt>Price range:</dt>
                                    <dd>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <input type="text" id="price-selector" name="price" value=""/>
                                            </div>
                                        </div>
                                    </dd>

                                    <dt>Condition:</dt>
                                    <dd>
                                        <div class="row">
                                            <div class="col-md-2">
                                                <input name="condition" type="checkbox" value="New"
                                                       data-toggle="toggle"
                                                       data-onstyle="warning"
                                                       data-on="New"
                                                       data-off="All"
                                                       data-width="75"
                                                       data-size="small"></div>

                                            <div class="col-md-3 text-right">
                                                <strong>Merchant:</strong>
                                                <input name="merchant" type="checkbox" value="Amazon"
                                                       data-toggle="toggle"
                                                       data-onstyle="warning"
                                                       data-on="Amazon"
                                                       data-off="All"
                                                       data-width="75"
                                                       data-size="small">
                                            </div>

                                            <div class="col-md-7 text-right">
                                                <button type="submit" class="btn btn-primary pull-right">
                                                    Search by filters!
                                                </button>
                                            </div>
                                        </div>
                                    </dd>

                                    </dd>
                                </dl>
                            </div>

                            <input name="form_key" type="hidden"
                                   value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                            <input name="node" type="hidden" value=""/>
                            <input name="isAjax" type="hidden" value="true"/>

                        </form>

                    </div>
                </div>
            </div>


            <!-- API Status Block -->
            <div class="col-md-6">
                <div class="panel block-eq panel-<?php echo $this->getAmazonConfig() ? 'info' : 'danger'; ?>">
                    <div class="panel-heading">
                        Amazon Account Settings
                        <span class="badge pull-right">
                            <?php echo $this->getAmazonConfig() ? 'connected' : 'disconnected'; ?>
                        </span>
                    </div>
                    <div class="panel-body">
                        <?php if ($this->getAmazonConfig()) : ?>
                            <dl class="dl-horizontal amazon-info col-md-8">
                                <dt>Access Key ID:</dt>
                                <dd><?php echo $this->getAmazonConfig('access_key_id'); ?></dd>

                                <dt>Secret Access Key:</dt>
                                <dd><?php echo $this->getAmazonConfig('secret_access_key'); ?></dd>

                                <dt>Partner Tag:</dt>
                                <dd><?php echo $this->getAmazonConfig('partner_tag'); ?></dd>
                            </dl>
                            <div class="col-md-4">
                                <img class="pull-right amazon-logo"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) .
                                         'adminhtml/default/default/amazonia/images/amazon-logo.png'; ?>"
                                />
                            </div>
                        <?php elseif ($this->getAmazonMessage()) : ?>
                            <div class="amazon-message well well-sm">
                                <?php echo $this->getAmazonMessage(); ?>
                            </div>
                        <?php endif; ?>
                    </div>

                </div>
            </div>

        </div>
    </div>


    <div class="col-md-12 results-block">
        <div class="row">

            <!-- Search Results -->
            <div class="col-md-12">

                <div class="panel panel-default no-border">
                    <div class="panel-heading bordered">

                        Search Results:
                        <span class="label label-success">
                            <span class="asins-counter success">0</span> success
                        </span>
                        <span class="label label-danger">
                            <span class="asins-counter failed">0</span> failed
                        </span>
                        <span class="label label-black remove-all">
                            remove failed?
                        </span>

                        <button class="add-ready-products btn btn-success btn-sm pull-right">Add ready products to
                            queue
                        </button>
                        <select name="attribute_set_id" class="pull-right form-control global" style="width: 220px">
                            <option value=""> &rarr; Set AttributeSet For All</option>
                            <?php /** @var Mage_Catalog_Model_Category $category */ ?>
                            <?php foreach ($this->getAttributeSets() as $attributeSet) : ?>
                                <option value="<?php echo $attributeSet->getId(); ?>">
                                    <?php echo $attributeSet->getAttributeSetName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <select name="category_id" class="pull-right form-control global" style="width: 220px">
                            <option value=""> &rarr; Set Category For All</option>
                            <?php /** @var Mage_Catalog_Model_Category $category */ ?>
                            <?php foreach ($this->getCategories() as $category) : ?>
                                <option value="<?php echo $category->getId(); ?>">
                                    <?php for ($i = 2, $offset = ''; $i < $category->getLevel(); $i++, $offset .= '..') : ?>
                                    <?php endfor; ?>
                                    <?php echo $offset . ' ' . $category->getName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                    <div>
                        <div id="results"></div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>


<div id="treeModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Please, select node for search:</h4>
            </div>
            <div class="modal-body">
                <form class="tree-form" action="<?php echo $this->getUrl('amazon/adminhtml_amazon/node/') ?>"
                      method="get">
                    <div id="tree"></div>
                    <input name="form_key" type="hidden"
                           value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                    <input name="isAjax" type="hidden" value="true"/>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">I confirm this node</button>
            </div>
        </div>

    </div>
</div>