<div id="loader"></div>

<div id="amazon-products-import">


    <div class="content-header">
        <table cellspacing="0">
            <tbody>
            <tr>
                <td>
                    <h3 class="icon-head head-products">Amazon. Products Import</h3>
                </td>
            </tr>
            </tbody>
        </table>
    </div>


    <div class="col-md-12">
        <div class="row">

            <!-- Search Block -->
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Product Search
                    </div>
                    <div class="panel-body block-eq">
                        <form action="<?php echo $this->getUrl('amazon/adminhtml_amazon/search/') ?>" method="post"
                              class="search-form">

                            <dl class="dl-horizontal col-md-12">
                                <dt>ASINs, space separated <br> or Amazon URL:</dt>
                                <dd>
                                    <input autofocus type="text" class="form-control" name="query"
                                           placeholder="What do you want import?">
                                    <button type="submit" class="btn btn-warning btn-sm pull-right">Just Do It!
                                    </button>
                                </dd>
                            </dl>

                            <input name="form_key" type="hidden"
                                   value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                            <input name="isAjax" type="hidden" value="true"/>

                        </form>
                    </div>
                </div>
            </div>


            <!-- API Status Block -->
            <div class="col-md-6">
                <div class="panel panel-<?php echo $this->getAmazonConfig() ? 'info' : 'danger'; ?>">
                    <div class="panel-heading">
                        Amazon Account Settings
                        <span class="badge pull-right">
                            <?php echo $this->getAmazonConfig() ? 'connected' : 'disconnected'; ?>
                        </span>
                    </div>
                    <div class="panel-body block-eq">
                        <?php if ($this->getAmazonConfig()) : ?>
                            <dl class="dl-horizontal col-md-8">
                                <dt>Access Key ID:</dt>
                                <dd><?php echo $this->getAmazonConfig('access_key_id'); ?></dd>

                                <dt>Secret Access Key:</dt>
                                <dd><?php echo $this->getAmazonConfig('secret_access_key'); ?></dd>

                                <dt>Partner Tag:</dt>
                                <dd><?php echo $this->getAmazonConfig('partner_tag'); ?></dd>
                            </dl>
                            <div class="col-md-4">
                                <img class="pull-right amazon-logo"
                                     src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) .
                                         'adminhtml/default/default/amazonia/images/amazon-logo.png'; ?>"
                                />
                            </div>
                        <?php elseif ($this->getAmazonMessage()) : ?>
                            <div class="amazon-message well well-sm">
                                <?php echo $this->getAmazonMessage(); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

        </div>
    </div>


    <div class="col-md-12 results-block">
        <div class="row">

            <!-- Search Results -->
            <div class="col-md-12">

                <div class="panel panel-default no-border">
                    <div class="panel-heading bordered">
                        Search Results:
                        <span class="label label-success">
                            <span class="asins-counter success">0</span> success
                        </span>
                        <span class="label label-danger">
                            <span class="asins-counter failed">0</span> failed
                        </span>
                        <span class="label label-black remove-all">
                            remove failed?
                        </span>
                        <button class="btn btn-warning btn-sm pull-right">Import ready products</button>
                        <select name="attribute_set_id" class="pull-right form-control global" style="width: 220px">
                            <option value=""> &rarr; Set AttributeSet For All</option>
                            <?php /** @var Mage_Catalog_Model_Category $category */ ?>
                            <?php foreach ($this->getAttributeSets() as $attributeSet) : ?>
                                <option value="<?php echo $attributeSet->getId(); ?>">
                                    <?php echo $attributeSet->getAttributeSetName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                        <select name="category_id" class="pull-right form-control global" style="width: 220px">
                            <option value=""> &rarr; Set Category For All</option>
                            <?php /** @var Mage_Catalog_Model_Category $category */ ?>
                            <?php foreach ($this->getCategories() as $category) : ?>
                                <option value="<?php echo $category->getId(); ?>">
                                    <?php for ($i = 2, $offset = ''; $i < $category->getLevel(); $i++, $offset .= '..') : ?>
                                    <?php endfor; ?>
                                    <?php echo $offset . ' ' . $category->getName(); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div>
                        <div id="results"></div>
                    </div>
                </div>

            </div>

        </div>
    </div>

</div>