<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Cookie/WriterInterface.php
 */

interface Brontosoftware_Magento_Core_Cookie_WriterInterface
{
    /**
     * Sets a cookie value
     * Note: The following default metadata; Values not mentioned are unset
     *
     * - httpOnly: true
     * - duration: one year
     * - path: /
     *
     * @param string $name
     * @param string $value
     * @param array $metadata
     * @return void
     */
    public function setServerCookie($name, $value, array $metadata = array());
}
