<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Store/ManagerInterface.php
 */

interface Brontosoftware_Magento_Core_Store_ManagerInterface
{
    /**
     * Gets a specific store
     *
     * @param mixed $storeId
     * @return mixed
     */
    public function getStore($storeId = null);

    /**
     * Gets the default store view
     *
     * @return mixed
     */
    public function getDefaultStoreView();

    /**
     * Gets all of the websites in the install
     *
     * @return array
     */
    public function getStores();

    /**
     * Gets a specific website
     *
     * @param mixed $websiteId
     * @return mixed
     */
    public function getWebsite($websiteId = null);

    /**
     * Gets all of the websites in the install
     *
     * @return array
     */
    public function getWebsites();

    /**
     * @return void
     */
    public function reinitStores();
}
