<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Store/UrlManagerInterface.php
 */

interface Brontosoftware_Magento_Core_Store_UrlManagerInterface
{
    /**
     * Creates a frontend url path for the given store
     *
     * @param mixed $store
     * @param string $path
     * @param array $params
     * @return string
     */
    public function getFrontendUrl($store, $path, $params = array());
}
