<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Magento/Core/Notification/InboxInterface.php
 */

interface Brontosoftware_Magento_Core_Notification_InboxInterface
{
    /**
     * Creates a Magento admin notification with information
     *
     * @param string $title
     * @param string $description
     * @param string $url
     * @return boolean
     */
    public function addNotice($title, $description, $url);

    /**
     * Marks the notification as read
     *
     * @param mixed $notificationId
     * @return void
     */
    public function markAsRead($notificationId);
}
